#listen port
port = 5000

# leveldb path
db = "data"

# util
log-dir = "log"
# log level: debug | info | warn | error
log-level = "info"
# log format: plain | json
log-format = "plain"

# user info
user-name = "ludete"
password = "12345678"

# wallet info
apikey = "bc9f49dde58089808ec2837c2efe7310"
secretkey = "6nU95IhOWpbymIWvVibiNyfTEblfqkDD0TbXIVEfD30"